import type { NextPage } from 'next'
import Head from 'next/head'
import Landing from '../components/landing';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>CloudyButts</title>
        <meta name="CloudedCrew NFTs" content="Generated by create next app" />
        <link rel="icon" href="/assets/logo_fla.png" />
      </Head>

      <Landing />

    </>
  )
}

export default Home
